package DBMS.UniSlot.Backend.dto.request;


import DBMS.UniSlot.Backend.enums.LectureDay;
import jakarta.validation.constraints.*;
import lombok.Data;

import java.time.LocalTime;
import java.util.List;

/**
 * DTO for admin to create one lecture slot group.
 *
 * A single "slot" typically runs on multiple days per week
 * (e.g., Monday + Wednesday). The admin submits the list of
 * days together; the service creates one LectureSlot row
 * per day, all sharing the same slotGroupCode.
 *
 * slotGroupCode is auto-generated by the service as:
 *   {courseCode}-{professorId}-{UUID_SHORT}
 */
@Data
public class CreateLectureSlotRequest {

    @NotNull(message = "Course ID is required")
    private Long courseId;

    @NotNull(message = "Professor ID is required")
    private Long professorId;

    /**
     * List of days this slot runs each week.
     * E.g., [MONDAY, WEDNESDAY] for a twice-weekly lecture.
     */
    @NotEmpty(message = "At least one day must be specified")
    private List<LectureDay> days;

    @NotNull(message = "Start time is required (HH:mm)")
    private LocalTime startTime;

    @NotNull(message = "End time is required (HH:mm)")
    private LocalTime endTime;

    @Size(max = 100)
    private String venue; // e.g., "LH-3"

    @NotNull(message = "Maximum capacity is required")
    @Min(value = 1,   message = "Capacity must be at least 1")
    @Max(value = 500, message = "Capacity cannot exceed 500")
    private Integer maxCapacity;
}
