package DBMS.UniSlot.Backend.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * ============================================================
 * LectureSlot  (maps to table: lecture_slots)
 * ============================================================
 * Represents one pickable slot for a course — the unit a student
 * enrols into.
 *
 * Example for OOP with 250 first-year CS students:
 *   OOP Slot 1 — Prof. Ali  — capacity 50
 *     lectures:  Mon 10:00–13:00 Room 101
 *   OOP Slot 2 — Prof. Ali  — capacity 50
 *     lectures:  Tue 09:00–10:00 Room 201
 *                Wed 14:00–16:00 Lab 3
 *   OOP Slot 3 — Prof. Sara — capacity 50
 *     lectures:  Mon 14:00–17:00 Room 305
 *   … (and so on for Slot 4, 5)
 *
 * Capacity & enrollment live HERE, not on individual lectures.
 * A student picks ONE slot and attends ALL its lectures.
 *
 * The slotGroupCode uniquely identifies this slot across the system.
 * ============================================================
 */
@Entity
@Table(name = "lecture_slots")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LectureSlot extends BaseEntity {

    // ── Course & Professor ────────────────────────────────────

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_id", nullable = false)
    private Course course;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "professor_id", nullable = false)
    private Professor professor;

    // ── Slot identity ─────────────────────────────────────────

    /**
     * Human-readable name shown to students.
     * E.g., "Slot 1", "Slot 2", "Section A".
     * Auto-generated by service if not provided.
     */
    @Column(name = "slot_name", nullable = false, length = 100)
    private String slotName;

    /**
     * Unique system code for this slot.
     * Format: {courseCode}-{profId}-{shortUUID}
     * Used in enrollment records and drop operations.
     */
    @Column(name = "slot_group_code", nullable = false, length = 80, unique = true)
    private String slotGroupCode;

    // ── Capacity & Enrollment ─────────────────────────────────

    @Column(name = "max_capacity", nullable = false)
    private Integer maxCapacity;

    @Column(name = "enrolled_count", nullable = false)
    @Builder.Default
    private Integer enrolledCount = 0;

    // ── Analytics timestamps ──────────────────────────────────

    @Column(name = "slot_opened_at")
    private LocalDateTime slotOpenedAt;

    @Column(name = "slot_filled_at")
    private LocalDateTime slotFilledAt;

    // ── Relationships ─────────────────────────────────────────

    /**
     * Individual lectures making up this slot's weekly schedule.
     * Each lecture can be on a different day, time, and venue.
     * Loaded eagerly since every slot view needs its schedule.
     */
    @OneToMany(mappedBy = "lectureSlot",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.EAGER)
    @Builder.Default
    private List<SlotLecture> lectures = new ArrayList<>();

    /** Student enrollments in this slot. */
    @OneToMany(mappedBy = "lectureSlot",
            cascade = CascadeType.ALL,
            fetch = FetchType.LAZY)
    @Builder.Default
    private List<SlotEnrollment> enrollments = new ArrayList<>();

    // ── Helpers ───────────────────────────────────────────────

    public boolean hasAvailableSeats() {
        return enrolledCount < maxCapacity;
    }

    public void incrementEnrollment() {
        if (!hasAvailableSeats()) {
            throw new IllegalStateException("Slot " + slotGroupCode + " is already full.");
        }
        this.enrolledCount++;
        if (this.enrolledCount >= this.maxCapacity && this.slotFilledAt == null) {
            this.slotFilledAt = LocalDateTime.now();
        }
    }

    public void decrementEnrollment() {
        if (this.enrolledCount > 0) {
            this.enrolledCount--;
            if (this.enrolledCount < this.maxCapacity) {
                this.slotFilledAt = null;
            }
        }
    }
}
