package DBMS.UniSlot.Backend.entity;

import DBMS.UniSlot.Backend.enums.InvoiceStatus;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * ============================================================
 * PaymentInvoice Entity  (maps to table: payment_invoices)
 * ============================================================
 * A billing record issued to a student each semester.
 * One PaymentInvoice per student per semester, generated by
 * the admin/finance team when semester registration opens.
 *
 * The invoice tracks:
 *  - total_due    — total amount owed (from SemesterFeeStructure)
 *  - amount_paid  — running total of payments received
 *  - balance      — total_due - amount_paid (computed on save)
 *  - status       — UNPAID / PARTIAL / PAID
 *
 * When status becomes PAID, the linked Student's feeStatus
 * is also updated to PAID, unlocking slot selection.
 * ============================================================
 */
@Entity
@Table(name = "payment_invoices",
        uniqueConstraints = @UniqueConstraint(columnNames = "invoice_number"))
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PaymentInvoice extends BaseEntity {

    /**
     * The student this invoice is issued to.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id", nullable = false)
    private Student student;

    /**
     * The fee structure that generated this invoice.
     * Determines the breakdown of charges.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fee_structure_id", nullable = false)
    private SemesterFeeStructure feeStructure;

    /**
     * Human-readable invoice number (e.g., "INV-2024-001234").
     * Printed on receipts.
     */
    @Column(name = "invoice_number", nullable = false, unique = true, length = 30)
    private String invoiceNumber;

    /** Total amount charged on this invoice. */
    @Column(name = "total_due", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalDue;

    /**
     * Cumulative amount paid so far.
     * Incremented each time a PaymentTransaction is recorded.
     */
    @Column(name = "amount_paid", nullable = false, precision = 10, scale = 2)
    @Builder.Default
    private BigDecimal amountPaid = BigDecimal.ZERO;

    /**
     * Remaining balance = totalDue - amountPaid.
     * Updated whenever a new transaction is posted.
     */
    @Column(name = "balance", nullable = false, precision = 10, scale = 2)
    private BigDecimal balance;

    /**
     * Current payment status.
     * Transitions: UNPAID → PARTIAL → PAID
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 10)
    @Builder.Default
    private InvoiceStatus status = InvoiceStatus.UNPAID;

    /** Last date to pay without penalty. */
    @Column(name = "due_date", nullable = false)
    private LocalDateTime dueDate;

    // ── Relationships ─────────────────────────────────────────

    /**
     * All payment transactions recorded against this invoice.
     * Multiple transactions are possible (e.g., two partial payments).
     */
    @OneToMany(mappedBy = "invoice",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.LAZY)
    @Builder.Default
    private List<PaymentTransaction> transactions = new ArrayList<>();

    // ── Business helpers ──────────────────────────────────────

    /**
     * Apply a payment amount to this invoice.
     * Updates amountPaid, balance, and status atomically.
     * Call this inside a @Transactional method.
     *
     * @param amount The amount being paid in this transaction.
     */
    public void applyPayment(BigDecimal amount) {
        this.amountPaid = this.amountPaid.add(amount);
        this.balance    = this.totalDue.subtract(this.amountPaid);
        if (this.balance.compareTo(BigDecimal.ZERO) <= 0) {
            this.balance = BigDecimal.ZERO;
            this.status  = InvoiceStatus.PAID;
        } else {
            this.status = InvoiceStatus.PARTIAL;
        }
    }

    /** @return true when the invoice is fully paid. */
    public boolean isFullyPaid() {
        return InvoiceStatus.PAID.equals(this.status);
    }
}